export const exampleData = [
  {
    id: "da1dsad2dasd",
    x: 0,
    y: 0,
    width: 45,
    height: 20.6,
    type: "pedalboards",
    elementID: "pedalboard",
    elementImage: "pb.png",
  },
  {
    id: "da1dsad2dasd",
    x: 0,
    y: 0,
    width: 9,
    height: 10.3,
    type: "pedals",
    elementID: "rat",
    elementImage: "rat.png",
  },
  {
    id: "da1asdasd2dasd",
    x: 0.614,
    y: 0.17,
    width: 9,
    height: 10.3,
    type: "pedals",
    elementID: "rat",
    elementImage: "rat.png",
  },
  {
    id: "da1sasdasd2dasd",
    x: 0.614,
    y: 0.17,
    width: 9,
    height: 10.3,
    type: "pedals",
    elementID: "rat",
    elementImage: "rat.png",
  },
  {
    id: "da1a23sdasd2dasd",
    x: 0.614,
    y: 0.17,
    width: 9,
    height: 10.3,
    type: "pedals",
    elementID: "rat",
    elementImage: "rat.png",
  },
  {
    id: "da1aasdsdasd2dasd",
    x: 0.614,
    y: 0.17,
    width: 9,
    height: 10.3,
    type: "pedals",
    elementID: "rat",
    elementImage: "rat.png",
  },
];
