export const exampleData = {
  c: {
    id: "pedalsid1",
    top: 0,
    left: 0,
    type: "pedalboards",
    Brand: "Blackbird",
    Name: "Tolex 1530",
    orientation: "0",
    layer: 1,
  },
  d: {
    id: "pedaaalassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  ds: {
    id: "pedaalassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  asd: {
    id: "pedasdalassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  dasd: {
    id: "pedasdalassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  asdd: {
    id: "pedasdalassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  aasdsdd: {
    id: "pedasdalassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  a3sdd: {
    id: "pedasdalassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  d34: {
    id: "pedaasd32lassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  d3: {
    id: "peda3q6lassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  d32fvd: {
    id: "pedalas76dsid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  sdf: {
    id: "pedalad7ssid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  asdasd: {
    id: "pedalas5d67sid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  d4df: {
    id: "pedalasdutsid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  sdfw43: {
    id: "pedalasetrsid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  as2: {
    id: "pedaystlassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
  ag34: {
    id: "pedals4yassid1",
    top: 0,
    left: 0,
    type: "pedals",
    Brand: "Pro Co",
    Name: "Rat",
    orientation: "0",
    layer: 1,
  },
};
// [
//   {
//     x: 0,
//     y: 0,
//     type: "pedalboards",
//     Brand: "Blackbird",
//     Name: "Tolex 1530",
//     orientation: "0",
//   },
//   {
//     id: "pedalsid1",
//     x: 0,
//     y: 0,
//     type: "pedals",
//     Brand: "Pro Co",
//     Name: "Rat",
//     orientation: "0",
//     layer: 1,
//   },
// ];
