export const exampleData = [
  {
    id: "pbiddadd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbiasddddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbidasdddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbiadsafgwedddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbid345ddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbid35ddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbi35fddddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbi34rgdddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbidd345fdd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbidd53fdd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbid345fdddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbi345sdfdddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbid345fuli78ddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbid345fddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbid345fd54tdd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbi34fwerdddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbifdsf4dddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbid345645ddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbidsdfsddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbidd534dd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbidew453ddd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  {
    id: "pbiddrwrwdd",
    x: 0,
    y: 0,
    type: "pedalboards",
    elementID: "pedalbasdoards",
    Brand: "Blackbird",
    Name: "Tolex 1224",
    orientation: "0",
    layer: 1,
  },
  // {
  //   id: "pedalsid1",
  //   x: 0,
  //   y: 0,
  //   type: "pedals",
  //   elementID: "rat",
  //   Brand: "Pro Co",
  //   Name: "Rat",
  //   orientation: "0",
  //   layer: 1,
  // },
];
